### ISSUE TITLE
I am getting wrong answer for testcases 3 and 4 can you please help me?

### ISSUE THREAD

**Issue by ghost** [motyim/ProblemSolve#2]
import java.util.Scanner;

/**
 * Created by jayanthsaikiran on 13/11/17.
 */
public class Day1 {
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int i=0,j=0,f=0,c1=0,c2=0,k=0;;
        String name[] = new String[n];
        String rate[] = new String[n];
        int a[] = new int[n];
        for(i=0;i<n;i++) {
            c1=0;c2=0;
            name[i] = sc.next();
            rate[i] = sc.next();
            for (j = 0; j < rate[i].length(); j++) {
                if (rate[i].charAt(j) == '4')
                    c1++;
                else if (rate[i].charAt(j) == '7')
                    c2++;
            }
            if (c1!=0&&c1==c2) {
                a[k++] = i;
            }
            else f--;
        }
        if(f==-n)
            System.out.println(-1);
        else {
            int t1,t2;
            c1 = a[0];
            for (j = 1; j < k; j++) {
                t1 = Integer.parseInt(rate[c1]);
                t2 = Integer.parseInt(rate[a[j]]);
                if(t1>t2);
                    c1 = a[j];
            }
            System.out.println(name[c1]+" "+rate[c1]);
        }
      }
}

**Comment by jayanthsaikiran** [comment]
import java.util.Scanner;

/**
 * Created by jayanthsaikiran on 13/11/17.
 */
public class Day1 {
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int i=0,j=0,f=0,c1=0,c2=0,k=0;;
        String name[] = new String[n];
        String rate[] = new String[n];
        int a[] = new int[n];
        for(i=0;i<n;i++) {
            c1=0;c2=0;
            name[i] = sc.next();
            rate[i] = sc.next();
            for (j = 0; j < rate[i].length(); j++) {
                if (rate[i].charAt(j) == '4')
                    c1++;
                else if (rate[i].charAt(j) == '7')
                    c2++;
            }
            if (c1!=0&&c1==c2) {
                a[k++] = i;
            }
            else f--;
        }
        if(f==-n)
            System.out.println(-1);
        else {
            int t1,t2;
            c1 = a[0];
            for (j = 1; j < k; j++) {
                t1 = Integer.parseInt(rate[c1]);
                t2 = Integer.parseInt(rate[a[j]]);
                if(t1>t2);
                    c1 = a[j];
            }
            System.out.println(name[c1]+" "+rate[c1]);
        }
      }
}
